
title: Austin Blackstone - Resume
url: 'http://blackstoneengineering.github.io'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Austin Blackstone
tagline: Developer Evangelist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: AustinBlackstoneEngineering@gmail.com
phone: 
website: austinblackstone.com #do not add http://
linkedin: austinblackstone
github: BlackstoneEngineering
twitter: engineer_austin

project-header: Full-stack engineer from chip to cloud. 
footer: |
  [view online - blackstoneengineering.github.io/resume](http://blackstoneengineering.github.io/resume)
# Update all the sections by editing the files inside _includes folder.

gtm: GTM-NC9RDMB

# Build settings
markdown: kramdown
permalink: pretty
