
title: Austin Blackstone - Resume
url: 'http://blackstoneengineering.github.io'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Austin Blackstone
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: austinblackstoneengineering@gmail.com
phone: 
website: austinblackstone.com #do not add http://
linkedin: austinblackstone
github: blackstoneengineering
twitter: engineer_austin

project-header: Jack of all trades covering embedded systems to web back end with a focus on evangelizing great technology. 
footer: |
  [view online - blackstoneengineering.github.io/resume](http://blackstoneengineering.github.io/resume)
# Update all the sections by editing the files inside _includes folder.

google-analytics-id: UA-47432525-2

# Build settings
markdown: kramdown
permalink: pretty
